version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama-data:/root/.ollama
    networks:
      - n8n-ollama-net

  n8n:
    image: n8nio/n8n:latest
    restart: always
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - ./volumes/n8n-data:/home/node/.n8n
    networks:
      - n8n-ollama-net
    
networks:
  n8n-ollama-net:
    driver: bridge
